### ISSUE TITLE
Spectator Mode

### ISSUE THREAD

**Issue by patel344** [jackieaskins/bananagrams#31]
The ability to view a game without participating.

Options:
1. Zoom style (choose a main board to watch, and others in a smaller screen and ability to choose between the two)
2. Show the top and worst players
3. Choose a board based on player name dropdown

**Comment by jackieaskins** [comment]
Spectator view added in 903c25ea203af8270e2e47232bacfa798de32a0b. Currently just displays all boards, will leave open until one of the 3 options above is added.
